### ISSUE TITLE
Soucis à l'installation de l'extension

### ISSUE THREAD

**Issue by waldeckio** [prrvchr/GContactOOo#1]
Bonjour, j'ai cette erreur 
(com.sun.star.uno.RuntimeException) { { Message = "<class 'ImportError'>: No module named 'mcontact' (or 'mcontact.checkVersion' is unknown), traceback follows\X000a  File \"C:\\Program Files\\LibreOffice\\program\\pythonloader.py\", line 147, in writeRegistryInfo\X000a    mod = self.getModuleFromUrl( locationUrl )\X000a  File \"C:\\Program Files\\LibreOffice\\program\\pythonloader.py\", line 102, in getModuleFromUrl\X000a    exec(codeobject, mod.__dict__)\X000a  File \"C:\\Users\\waldeck\\AppData\\Roaming\\LibreOffice\\4\\user\\uno_packages\\cache\\uno_packages\\lu124413m2.tmp_\\gContactOOo (1).oxt\\service\\Driver.py\", line 49, in <module>\X000a    from mcontact import checkVersion\X000a  File \"C:\\Program Files\\LibreOffice\\program\\uno.py\", line 425, in _uno_import\X000a    raise uno_import_exc\X000a  File \"C:\\Program Files\\LibreOffice\\program\\uno.py\", line 346, in _uno_import\X000a    return _builtin_import(name, *optargs, **kwargs)\X000a\X000a", Context = (com.sun.star.uno.XInterface) @0 } }

J'ai python 3.11.6 qui vient du store de Microsoft, je suis sous Windows 11 j'ai jre 11.0.20.1 comme vous le recommandez.

Merci pour votre aide.

**Comment by prrvchr** [comment]
Salut waldeckio,

> Bonjour, j'ai cette erreur
> (com.sun.star.uno.RuntimeException) { { Message = "<class 'ImportError'>: No module named 'mcontact' (or ...

Grossière erreur que je viens de corriger, désolé du dérangement, et merci d'avoir pris la peine de signaler le dysfonctionnement...
Il faut télécharger à nouveau l'extension, le numéro de version est resté inchangé..

> J'ai python 3.11.6 qui vient du store de Microsoft, je suis sous Windows 11 j'ai jre 11.0.20.1 comme vous le recommandez.

La version jre 11 est nécessaire, par contre sous Windows (et uniquement sous Windows) python n'est pas nécessaire car LibreOffice utilise sa propre version (3.8, je crois) qui l'accompagne.

Je me permets de fermer ce dysfonctionnement, merci d'en ouvrir un nouveau si nécessaire.
